### ISSUE TITLE
Use Gradle as a build system and Kotlin as a language

### ISSUE THREAD

**Issue by vityaman** [secs-dev/itmo-dating#33]
Reading `Maven` files is hard. Migrate build to `Gradle` using `Kotlin DSL`.

## Steps

- [x] Build using Gradle
- [x] Translate Java to Kotlin
- [x] Add Kotlin linters and formatters

## References

- https://github.com/vityaman-edu/nexo-hub
- https://github.com/vityaman-edu/lms

## Talks

Все стримы Mobile Developer по изучению, ответам на вопросы Gradle сборки.

В |1| Нозик рассказывает основы работы сборщика проекта, в частности Gradle на Kotlin, годится для чуть более осмысленного использования. Дает понимание, почему именно Gradle, а не другие системы. 

В |2|, |3|, |4| разработчик из JB рассказывает, как писать свои сборки и как изучать сборки имеющихся проектов. Так же показывает, как искать документацию. На мой взгляд, |4| наиболее информативное видео, которое показывает, насколько Gradle сложная штука, и объясняет концепции заложенные в него.

[1] https://www.youtube.com/live/nKC0qmOyiws 
[2] https://www.youtube.com/live/YVz1ZuNR1rQ
[3] https://www.youtube.com/live/HZLwlWZViFk
[4] https://www.youtube.com/live/S7Ogpp181jM
